//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Email.MessageValidationResources", typeof(MessageValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; .
        /// </summary>
        internal static string HelperSummarySeparator {
            get {
                return ResourceManager.GetString("HelperSummarySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the &apos;{0}&apos; character, found at column {1}.
        /// </summary>
        internal static string InvalidCharacterDetailFormat {
            get {
                return ResourceManager.GetString("InvalidCharacterDetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more characters did not fall within the {0} character range. Details: {1}. See http://tools.ietf.org/html/rfc5322#section-2.1 for more information..
        /// </summary>
        internal static string InvalidStringHelperSummaryFormat {
            get {
                return ResourceManager.GetString("InvalidStringHelperSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line length ({0}) exceeded maximum length ({1}) as specified by RFC 5322, Section 2.1.1. See http://tools.ietf.org/html/rfc5322#section-2.1.1 for more information..
        /// </summary>
        internal static string MaxLineLengthExceededFormat {
            get {
                return ResourceManager.GetString("MaxLineLengthExceededFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line length ({0}) exceeded recommended maximum length ({1}) as specified by RFC 5322, Section 2.1.1. See http://tools.ietf.org/html/rfc5322#section-2.1.1 for more information..
        /// </summary>
        internal static string RecommendedLineLengthExceededFormat {
            get {
                return ResourceManager.GetString("RecommendedLineLengthExceededFormat", resourceCulture);
            }
        }
    }
}
